// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/sign-in/*": {
    params: {
      "*": string;
    };
  };
  "/sign-up/*": {
    params: {
      "*": string;
    };
  };
  "/acceuil": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/commandes": {
    params: {};
  };
  "/ventes": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/notifications": {
    params: {};
  };
  "/achats": {
    params: {};
  };
  "/travailleurs": {
    params: {};
  };
  "/clients": {
    params: {};
  };
  "/fournisseurs": {
    params: {};
  };
  "/articles": {
    params: {};
  };
  "/promotions": {
    params: {};
  };
  "/caisses": {
    params: {};
  };
  "/aides": {
    params: {};
  };
  "/parametres": {
    params: {};
  };
  "/admin/businesses": {
    params: {};
  };
  "/admin/offres": {
    params: {};
  };
  "/admin/categories": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/sign-in/*" | "/sign-up/*" | "/acceuil" | "/dashboard" | "/commandes" | "/ventes" | "/profile" | "/notifications" | "/achats" | "/travailleurs" | "/clients" | "/fournisseurs" | "/articles" | "/promotions" | "/caisses" | "/aides" | "/parametres" | "/admin/businesses" | "/admin/offres" | "/admin/categories";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./auth/sign-in/[[...sign-in]]/page.tsx": {
    id: "auth/sign-in/[[...sign-in]]/page";
    page: "/sign-in/*";
  };
  "./auth/sign-up/[[...sign-up]]/page.tsx": {
    id: "auth/sign-up/[[...sign-up]]/page";
    page: "/sign-up/*";
  };
  "./routes/acceuil/acceuil.tsx": {
    id: "routes/acceuil/acceuil";
    page: "/acceuil";
  };
  "./routes/dashboard/dashboard.tsx": {
    id: "routes/dashboard/dashboard";
    page: "/dashboard";
  };
  "./routes/commandes/commandes.tsx": {
    id: "routes/commandes/commandes";
    page: "/commandes";
  };
  "./routes/ventes/ventes.tsx": {
    id: "routes/ventes/ventes";
    page: "/ventes";
  };
  "./routes/profile/profile.tsx": {
    id: "routes/profile/profile";
    page: "/profile";
  };
  "./routes/notifications/notifications.tsx": {
    id: "routes/notifications/notifications";
    page: "/notifications";
  };
  "./routes/achats/achats.tsx": {
    id: "routes/achats/achats";
    page: "/achats";
  };
  "./routes/travailleurs/travailleurs.tsx": {
    id: "routes/travailleurs/travailleurs";
    page: "/travailleurs";
  };
  "./routes/clients/clients.tsx": {
    id: "routes/clients/clients";
    page: "/clients";
  };
  "./routes/fournisseurs/fournisseurs.tsx": {
    id: "routes/fournisseurs/fournisseurs";
    page: "/fournisseurs";
  };
  "./routes/articles/articles.tsx": {
    id: "routes/articles/articles";
    page: "/articles";
  };
  "./routes/promotions/promotions.tsx": {
    id: "routes/promotions/promotions";
    page: "/promotions";
  };
  "./routes/caisses/caisses.tsx": {
    id: "routes/caisses/caisses";
    page: "/caisses";
  };
  "./routes/aides/aides.tsx": {
    id: "routes/aides/aides";
    page: "/aides";
  };
  "./routes/parametres/parametres.tsx": {
    id: "routes/parametres/parametres";
    page: "/parametres";
  };
  "./routes/admin/businesses.tsx": {
    id: "routes/admin/businesses";
    page: "/admin/businesses";
  };
  "./routes/admin/offres.tsx": {
    id: "routes/admin/offres";
    page: "/admin/offres";
  };
  "./routes/admin/categories.tsx": {
    id: "routes/admin/categories";
    page: "/admin/categories";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/./routes/home.tsx");
  "auth/sign-in/[[...sign-in]]/page": typeof import("./app/./auth/sign-in/[[...sign-in]]/page.tsx");
  "auth/sign-up/[[...sign-up]]/page": typeof import("./app/./auth/sign-up/[[...sign-up]]/page.tsx");
  "routes/acceuil/acceuil": typeof import("./app/./routes/acceuil/acceuil.tsx");
  "routes/dashboard/dashboard": typeof import("./app/./routes/dashboard/dashboard.tsx");
  "routes/commandes/commandes": typeof import("./app/./routes/commandes/commandes.tsx");
  "routes/ventes/ventes": typeof import("./app/./routes/ventes/ventes.tsx");
  "routes/profile/profile": typeof import("./app/./routes/profile/profile.tsx");
  "routes/notifications/notifications": typeof import("./app/./routes/notifications/notifications.tsx");
  "routes/achats/achats": typeof import("./app/./routes/achats/achats.tsx");
  "routes/travailleurs/travailleurs": typeof import("./app/./routes/travailleurs/travailleurs.tsx");
  "routes/clients/clients": typeof import("./app/./routes/clients/clients.tsx");
  "routes/fournisseurs/fournisseurs": typeof import("./app/./routes/fournisseurs/fournisseurs.tsx");
  "routes/articles/articles": typeof import("./app/./routes/articles/articles.tsx");
  "routes/promotions/promotions": typeof import("./app/./routes/promotions/promotions.tsx");
  "routes/caisses/caisses": typeof import("./app/./routes/caisses/caisses.tsx");
  "routes/aides/aides": typeof import("./app/./routes/aides/aides.tsx");
  "routes/parametres/parametres": typeof import("./app/./routes/parametres/parametres.tsx");
  "routes/admin/businesses": typeof import("./app/./routes/admin/businesses.tsx");
  "routes/admin/offres": typeof import("./app/./routes/admin/offres.tsx");
  "routes/admin/categories": typeof import("./app/./routes/admin/categories.tsx");
};